POST http://localhost:3333/api/links
Content-Type: application/json

{
  "code": "resume",
  "url":"https://resume-huannvictor.vercel.app/"
}

###

GET http://localhost:3333/api/links
Content-Type: application/json

###
GET http://localhost:3333/resume